name: Custom Action
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run custom action
        uses: ZakBrinlee/custom-action@main